In [1]:
!pip install pandas duckdb jupysql

Requirement already satisfied: pandas in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: duckdb in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (1.5.1)
Collecting jupysql
  Downloading jupysql-0.11.1-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: prettytable>=3.12.0 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from jupysql) (3.17.0)
Requirement already satisfied: sqlalchemy in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from jupysql) (2.0.48)
Requirement already satisfied: sqlparse in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from jupysql) (0.5.3)
Requirement already satisfied: ipython-genutils>=0.1.0 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from jupysql) (3.1.4)
Collecting sqlglot>=11.3.7 (from jupysql)
  Downloading sqlglot-30.2.1-py3-none-any.whl.metadata (24 kB)
Collecting jupysql-plugin>=0.4.2 (from jupysql)
  Downloading jupysql_plugin-0.4.5-py3-none-any.whl.metadata (7.8 kB)
Collecting ploomber-core>=0.2.7 (from jupysql)
  Downloading ploomber_core-0.2.27-py3-none-any.whl.metadata (532 bytes)
Requirement already satisfied: pyyaml in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from ploomber-core>=0.2.7->jupysql) (6.0.1)
Collecting posthog>=3.0 (from ploomber-core>=0.2.7->jupysql)
  Downloading posthog-7.9.12-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: wcwidth in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from prettytable>=3.12.0->jupysql) (0.2.5)
Requirement already satisfied: six>=1.5 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from jinja2->jupysql) (2.1.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from sqlalchemy->jupysql) (4.12.2)
Requirement already satisfied: requests<3.0,>=2.7 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.32.2)
Collecting backoff>=1.10.0 (from posthog>=3.0->ploomber-core>=0.2.7->jupysql)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: distro>=1.5.0 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/isaakjiang/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2025.1.31)
Downloading jupysql-0.11.1-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.1/95.1 kB 4.8 MB/s eta 0:00:00
Downloading jupysql_plugin-0.4.5-py3-none-any.whl (192 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.8/192.8 kB 9.4 MB/s eta 0:00:00
Downloading ploomber_core-0.2.27-py3-none-any.whl (22 kB)
Downloading sqlglot-30.2.1-py3-none-any.whl (668 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 668.6/668.6 kB 17.6 MB/s eta 0:00:00
Downloading posthog-7.9.12-py3-none-any.whl (202 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.5/202.5 kB 12.2 MB/s eta 0:00:00
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Installing collected packages: sqlglot, backoff, posthog, ploomber-core, jupysql-plugin, jupysql
Successfully installed backoff-2.2.1 jupysql-0.11.1 jupysql-plugin-0.4.5 ploomber-core-0.2.27 posthog-7.9.12 sqlglot-30.2.1

In [2]:
import pandas as pd
import sqlite3

base_raw_url = "https://raw.githubusercontent.com/isaakzyjiang/BAML-coursework/main/SQL/datas/"

files = ["addresses.csv", "customers.csv", "orders.csv", "products.csv", "suppliers.csv"]

conn = sqlite3.connect("mydatabase.db")

print("Starting data migration from GitHub...")

for file_name in files:
    url = base_raw_url + file_name
    table_name = file_name.replace(".csv", "")
    
    try:
        df = pd.read_csv(url)
        df.to_sql(table_name, conn, if_exists='replace', index=False)
        print(f"Successfully imported table: [{table_name}]")
    except Exception as e:
        print(f"Failed to import {file_name}: {e}")

# Close the connection after processing
conn.close()
print("\nAll data is now stored in 'mydatabase.db'. You can start writing SQL!")

Starting data migration from GitHub...
Successfully imported table: [addresses]
Successfully imported table: [customers]
Successfully imported table: [orders]
Successfully imported table: [products]
Successfully imported table: [suppliers]

All data is now stored in 'mydatabase.db'. You can start writing SQL!

In [ ]:
%load_ext sql

%sql sqlite:///mydatabase.db

%config SqlMagic.autopandas = True

Fontconfig warning: ignoring UTF-8: not a valid region tag

Connecting to 'sqlite:///mydatabase.db'

Check if it works: simple select * from products

In [7]:
%%sql

select *
from products
limit 5

Running query in 'sqlite:///mydatabase.db'

    ID        Name  Stock  SellingPrice  SupplierPrice  SupplierID
0    1      Iphone     20          1200           1000           1
1   14      Laptop     18           800            600           2
2   32  Headphones      3           600            400           3
3   64          TV      5          1400           1200           4
4  754  Smartwatch     18           301             62           2

Select all products with supplier cost greater 200 and sort them according to the costs in descending order.

In [9]:
%%sql

select *
from products
where SupplierPrice > 200
order by SupplierPrice DESC

Running query in 'sqlite:///mydatabase.db'

     ID              Name  Stock  SellingPrice  SupplierPrice  SupplierID
0    64                TV      5          1400           1200           4
1     1            Iphone     20          1200           1000           1
2    14            Laptop     18           800            600           2
3   396        VR Headset      7           596            487           2
4   703        Power Bank      1           736            464           5
5   877           Monitor     22           565            407           3
6    32        Headphones      3           600            400           3
7   171   Fitness Tracker     50           496            388           1
8   373  Smart Thermostat     11           573            361           2
9   467            Router      3           476            359           6
10  733       Smart Light     46           444            345           6
11  847         Projector     25           405            324           8
12  489          E-Reader     24           494            282           5
13  833             Drone     29           370            264           9
14  266      External SSD     43           334            231           6

Select all orders from April, 2025 with an order total below 1000 euros. Sort according to order total ascending order

In [18]:
%%sql

select *
from orders
where Date >= '2025-04-01' and Date < '2025-05-01'
and (Qty*UnitPrice) < 1000
order by (Qty*UnitPrice) ASC

Running query in 'sqlite:///mydatabase.db'

,OrderID,Date,ProductID,CustomerID,ShippingAddressID,IBAN,Qty,UnitPrice
0,10951,2025-04-28,444,8770,2,GB76SORK24914168601347,1,244.00
1,10287,2025-04-27,646,4630,28,GB79MTUQ49027703843098,1,301.00
2,10409,2025-04-14,754,6119,13,GB93IQVN40155778817884,1,301.00
3,10562,2025-04-06,754,8560,38,GB93NFNI48869461195243,1,301.00
4,10708,2025-04-05,754,6119,24,GB77XHBC02724055934296,1,301.00
5,10995,2025-04-27,646,8381,3,GB18XXIF44626325144881,1,301.00
6,10979,2025-04-26,350,8560,8,GB42VCYK06662670551437,1,359.00
7,10658,2025-04-24,833,1710,3,GB64GIFG46199423767694,1,370.00
8,10843,2025-04-06,833,4886,6,GB70WWZP43811995376601,1,370.00
9,10883,2025-04-17,180,8438,4,GB44YTNB33582686270369,1,391.76
10,10146,2025-04-21,847,7947,7,GB28GLKN09320489964235,1,405.00
11,10237,2025-04-18,847,8381,33,GB23ZMAH32309821506489,1,405.00
12,10259,2025-04-26,733,7511,4,GB69KTBY94798515832818,1,444.00
13,10628,2025-04-22,384,7594,35,GB61SQJW36241862369036,1,455.00
14,10790,2025-04-23,384,7566,8,GB48REMT11633194226865,1,455.00
15,10093,2025-04-06,467,9850,6,GB26YTET62229270653794,1,476.00
16,10710,2025-04-12,444,7797,4,GB61IKWR81056974132834,2,244.00
17,10906,2025-04-16,489,5831,10,GB04EKZU93993379705816,1,494.00
18,10180,2025-04-08,171,5831,9,GB56UJFI15415206436110,1,496.00
19,10978,2025-04-08,877,8438,34,GB78HOED88566695413297,1,565.00
20,10103,2025-04-02,792,8770,23,GB57UKID56676527758416,2,295.00
21,10691,2025-04-25,792,2501,5,GB74DJMP23849791620223,2,295.00
22,10823,2025-04-29,792,2501,1,GB27GYLA27160736077633,2,295.00
23,10175,2025-04-02,132,7511,9,GB78DYZH39596292330958,3,202.00
24,10671,2025-04-03,833,2501,6,GB28SUDE71130724078754,2,370.00
25,10780,2025-04-28,617,1841,2,GB22WSIG89760740177509,3,256.00
26,10871,2025-04-08,847,1710,1,GB82NVSW43460666437490,2,405.00
27,10049,2025-04-24,733,7566,18,GB79IZZU93618324210249,2,444.00
28,10351,2025-04-27,754,1841,32,GB29BCYJ55616814721458,3,301.00
29,10844,2025-04-01,646,7594,5,GB62YIXX44856451017397,3,301.00
30,10969,2025-04-02,171,8245,6,GB70SZYX24632037476775,2,496.00

Calculate the total revenue in April 2025

In [20]:
%%sql

select sum(Qty*UnitPrice) as TotalRevenue
from orders
where Date >= '2025-04-01' and Date < '2025-05-01'

Running query in 'sqlite:///mydatabase.db'

   TotalRevenue
0     119253.71

Select the total revenue per customer

In [23]:
%%sql

select CustomerID, sum(Qty*UnitPrice) as TotalRevenue
from orders
group by CustomerID

Running query in 'sqlite:///mydatabase.db'

    CustomerID  TotalRevenue
0         1018      44425.99
1         1042      44674.28
2         1710      49184.01
3         1841      36577.16
4         2501      50356.33
5         2612      53557.18
6         3248      55952.35
7         3344      40017.08
8         3939      35599.39
9         4630      41163.65
10        4886      53137.00
11        4912      64710.00
12        5831      65828.00
13        6119      60117.03
14        6295      55319.48
15        6977      52140.43
16        7511      38560.10
17        7566      80419.07
18        7594      52812.28
19        7626      55298.84
20        7797      48365.10
21        7947      49642.06
22        8245      45113.49
23        8381      64160.70
24        8438      57425.22
25        8486      66910.67
26        8560      54456.83
27        8606      45606.20
28        8770      42013.83
29        9850      47983.00

Select the total revenue per customer but include only customers with an average revenue below 5000

In [24]:
%%sql

select CustomerID, sum(Qty*UnitPrice) as TotalRevenue
from orders
group by CustomerID
having avg(Qty*UnitPrice) < 5000

Running query in 'sqlite:///mydatabase.db'

    CustomerID  TotalRevenue
0         1018      44425.99
1         1042      44674.28
2         1710      49184.01
3         1841      36577.16
4         2501      50356.33
5         2612      53557.18
6         3248      55952.35
7         3344      40017.08
8         3939      35599.39
9         4630      41163.65
10        4886      53137.00
11        4912      64710.00
12        5831      65828.00
13        6119      60117.03
14        6295      55319.48
15        6977      52140.43
16        7511      38560.10
17        7566      80419.07
18        7594      52812.28
19        7626      55298.84
20        7797      48365.10
21        7947      49642.06
22        8245      45113.49
23        8381      64160.70
24        8438      57425.22
25        8486      66910.67
26        8560      54456.83
27        8606      45606.20
28        8770      42013.83
29        9850      47983.00

Calculate revenue per product. The output should include the product name and the total revenue per product. Sort the output by revenue, descending order.

In [31]:
%%sql

select P.Id, P.Name, sum(O.Qty*O.UnitPrice) as TotalRevenue
from products P, orders O
where P.ID = O.ProductID
group by P.ID
order by TotalRevenue DESC

Running query in 'sqlite:///mydatabase.db'

     ID               Name  TotalRevenue
0     1             Iphone     170130.25
1    64                 TV     143109.06
2   703         Power Bank     114355.75
3    14             Laptop     108331.78
4   489           E-Reader      82766.92
5   877            Monitor      78463.78
6   467             Router      74393.75
7   373   Smart Thermostat      72601.74
8   733        Smart Light      64305.01
9    32         Headphones      62101.00
10  396         VR Headset      61111.77
11  171    Fitness Tracker      58769.16
12  384            USB Hub      51777.77
13  833              Drone      48521.23
14  266       External SSD      48383.80
15  350             Tablet      46670.00
16  180           Soundbar      46667.81
17  847          Projector      41310.00
18  617    Gaming Keyboard      40551.20
19  754         Smartwatch      36405.96
20  444             Webcam      28197.44
21  132     Wireless Mouse      25944.86
22  646     Smart Doorbell      25121.71
23  792  Bluetooth Speaker      21535.00

Get the number of products ordered per country.

In [36]:
%%sql

select C.country, sum(O.Qty) as ProductCount
from customers C, orders O
where C.CustomerID = O.CustomerID
group by C.country

Running query in 'sqlite:///mydatabase.db'

         country  ProductCount
0         France           810
1        Germany           799
2          Italy           470
3          Spain           685
4  United States           233

Find all orders with their shipping address details.

In [43]:
%%sql

select O.OrderID, A.*
from orders O, addresses A
where O.CustomerID = A.CustomerID
group by O.OrderID

Running query in 'sqlite:///mydatabase.db'

,OrderID,CustomerID,Street,City,State,PostalCode,Country,AddressID
0,10000,8438,"11, rue de Leleu",Chevalier,None,16475,France,4
1,10001,8560,"24, rue Océane Gimenez",Sainte Maurice,None,330,France,38
2,10002,6119,Canale Gionata 1 Piano 8,Costalonga del friuli,Campobasso,60256,Italy,24
3,10003,4886,Lilian-Mülichen-Straße 11,Jessen,Sachsen-Anhalt,70106,Germany,14
4,10004,1018,"701, avenue Vidal",Sainte Alex,None,37556,France,37
...,...,...,...,...,...,...,...,...
995,10995,8381,"689, boulevard Sylvie Fouquet",Launaydan,None,77434,France,33
996,10996,7594,Klappplatz 1,Perleberg,Mecklenburg-Vorpommern,76483,Germany,5
997,10997,2501,Heßplatz 3,Leipziger Land,Bremen,75107,Germany,19
998,10998,7594,Klappplatz 1,Perleberg,Mecklenburg-Vorpommern,76483,Germany,5
999,10999,7626,Pasadizo Ángela Figueras 26 Puerta 5,Sevilla,Baleares,84656,Spain,28

Calculate revenue per supplier. The output should include the supplier name and the total revenue.

In [49]:
%%sql

select S.Name, sum(O.Qty*O.UnitPrice) as TotalRevenue
from suppliers S, products P, orders O
where S.SupplierID = P.SupplierID and P.ID = O.ProductID
group by S.Name

Running query in 'sqlite:///mydatabase.db'

                              Name  TotalRevenue
0                     Abbott-Munoz     187082.56
1                   Blake and Sons     116724.04
2                   Davis and Sons     197122.67
3                        Doyle Ltd     306648.69
4   Gardner, Robinson and Lawrence      41310.00
5      Guzman, Hoffman and Baldwin     214900.77
6     Henderson, Ramirez and Lewis      40551.20
7    Mcclain, Miller and Henderson     254844.27
8  Rodriguez, Figueroa and Sanchez     192342.55

Select all customers who ordered at least one product with Qty > *3*

In [55]:
%%sql

select *
from customers C
where exists (
    select *
    from orders O
    where O.CustomerID = C.CustomerID
    and O.Qty > 3
)

Running query in 'sqlite:///mydatabase.db'

    CustomerID                        CustomerName        country
0         3939                          Agnes Trub        Germany
1         1841                      Veronica Naser        Germany
2         8381                   Elizabeth Chapman  United States
3         8438                        Zacharie Rey         France
4         7594           Philippe-Richard Teixeira         France
5         8245                Éric-Stéphane Nguyen         France
6         1018                  Henrike Bloch B.A.        Germany
7         8560              Moisés Correa Valentín          Spain
8         1042                      Miroslawa Huhn        Germany
9         4912                 Fátima Guillen-Reig          Spain
10        8486                      Emilio Platini          Italy
11        2612                     Helfried Geisel        Germany
12        3344  Dipl.-Ing. Marco Hermighausen MBA.        Germany
13        4886                      Lea Klemt-Rust        Germany
14        6977                     Benjamin Collet         France
15        7511             Mathilde Robin-Delaunay         France
16        8606      Moreno Hernando Carnero Chaves          Spain
17        7797                 Sigfrido Tovar Raya          Spain
18        2501              Marijan Segebahn B.Sc.        Germany
19        9850                    Sabas Díaz-Canet          Spain
20        1710                  Madeleine du Weiss         France
21        5831                   Ligia Ros Cabezas          Spain
22        8770                     Carlo Bresciani          Italy
23        6119                    Caroline Verdier         France
24        7566                       Elmo Baglioni          Italy
25        7947       María Dolores Salamanca Ribas          Spain
26        3248                        Donna Wilson  United States
27        7626                 Ing. Belinda Ladeck        Germany
28        4630                      Denise Garnier         France
29        6295              Greca Coppola-Rosselli          Italy

Join the data of all tables from May 2025 into a single table.

In [56]:
%%sql

select *
from orders O, customers C, addresses A, products P, suppliers S
where S.SupplierID = P.SupplierID
and P.ID = O.ProductID
and A.CustomerID = O.CustomerID
and C.CustomerID = O.CustomerID
and O.Date >= '2025-05-01' and O.Date < '2025-06-01'

Running query in 'sqlite:///mydatabase.db'

,OrderID,Date,ProductID,CustomerID,ShippingAddressID,IBAN,Qty,UnitPrice,CustomerID,CustomerName,...,AddressID,ID,Name,Stock,SellingPrice,SupplierPrice,SupplierID,SupplierID,Name,Email
0,10112,2025-05-01,733,7594,35,GB09QJCI38424981829922,2,444.0,7594,Philippe-Richard Teixeira,...,5,733,Smart Light,46,444,345,6,6,Abbott-Munoz,abbott-munoz@example.com
1,10112,2025-05-01,733,7594,35,GB09QJCI38424981829922,2,444.0,7594,Philippe-Richard Teixeira,...,35,733,Smart Light,46,444,345,6,6,Abbott-Munoz,abbott-munoz@example.com

List orders where the UnitPrice is greater than the SelingPrice.

In [60]:
%%sql

select *
from orders O
where UnitPrice > (
    select SellingPrice
    from products P
    where O.productID = P.ID
)

Running query in 'sqlite:///mydatabase.db'

,OrderID,Date,ProductID,CustomerID,ShippingAddressID,IBAN,Qty,UnitPrice
0,10096,2024-06-27,132,2612,10,GB92NCHO50606853615305,2,228.69
1,10139,2025-04-30,754,1018,7,GB70XYDB69033119079030,4,360.08
2,10174,2025-02-26,733,6119,15,GB58RLRY07836134074517,5,478.97
3,10198,2024-10-28,373,7566,2,GB28KNDR53747411249035,5,629.86
4,10299,2024-08-06,14,7594,35,GB43RSBM12034717545588,5,903.58
5,10312,2024-09-27,14,8486,5,GB93YOHX03718376452088,3,954.42
6,10319,2025-01-11,489,1042,39,GB41CBEF03173109678994,3,530.76
7,10439,2024-10-15,180,1710,17,GB93DMOK67700284276246,5,477.21
8,10513,2024-07-14,877,8381,3,GB69VAWV89487060566418,5,584.14
9,10521,2024-12-13,489,8245,36,GB31RYEE74954508920388,4,533.66
10,10527,2025-01-25,617,1841,2,GB10LKTN30993842530428,3,290.40
11,10549,2025-04-28,754,8606,9,GB27RMND33155206506373,4,340.30
12,10601,2024-09-11,467,8560,38,GB94QAYV30569067447163,5,503.55
13,10626,2024-06-27,132,6119,11,GB32LECH10962272847657,5,224.62
14,10636,2025-01-31,703,8245,6,GB79YOIP47219705466927,5,746.58
15,10737,2025-04-05,14,7626,10,GB58JVPP69587413146753,2,875.31
16,10901,2025-02-11,171,1710,17,GB11YMNA25626506229231,4,556.29
17,10902,2024-05-07,384,6977,11,GB32MPEI53076248433797,1,457.45
18,10924,2024-11-03,373,8486,1,GB10CXWE31660076762090,4,602.86
19,10947,2025-03-21,32,3939,31,GB12RTKJ78769899927517,1,642.52
20,10973,2024-12-14,1,8560,38,GB88DOYP68089812657422,4,1423.02